spring.application.name=demoMail

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jcscom13@gmail.com
spring.mail.password=1q2w3e4r5t^Y
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true